[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "raftengine-sqlitelog"
version = "0.5.0" 
description = "SQLite log companion for raftengine"
authors = [{ name = "Dennis Parker", email = "dlukeparker@windhavengroup.com" }]
license = { file = "../../LICENSE.md" }  
requires-python = ">=3.11"  
dependencies = ["raftengine"]  

[tool.hatch.build.targets.wheel]
packages = ["src/sqlite_log"]