[project]
name = "raftengine-logs-hybrid"
version = "0.5.2"
requires-python = ">=3.11"
dependencies = [
    "raftengine>=0.2.0",
    "lmdb>=1.7.3",
]
description = "Hybrid LMDB+SQLite log implementation for raftengine"
authors = [{ name = "Dennis Parker", email = "dlukeparker@windhavengroup.com" }]
license = "MIT"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["raftengine_logs*"]