[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "raftengine-lmdblog"
version = "0.5.0" 
description = "LMDB based log companion for raftengine"
authors = [{ name = "Dennis Parker", email = "dlukeparker@windhavengroup.com" }]
license = { file = "../../LICENSE.md" }  
requires-python = ">=3.11"  
dependencies = ["raftengine", "lmdb"]  



[tool.hatch.build.targets.wheel]
packages = ["src/lmdb_log"]